### PR TITLE
Bump Quarkus and OpenTelemetry

### PR DESCRIPTION
**Pull request by jeanbisutti**

### CODE REVIEW

**Comment by jeanbisutti** [comment]
@brunobat The OTel Jaeger exporter has been removed: https://github.com/open-telemetry/opentelemetry-java/pull/6119

**Comment by brunobat** [comment]
I guess we will need to remove that exporter... Will send a deprecation for removal notice. 
Another lovely breaking change.

**Comment by jeanbisutti** [comment]
@brunobat The Azure tests are now working, but not the GCP ones.

**Comment by brunobat** [comment]
We need to bump the GCP version... Will look into it

**Comment by brunobat** [comment]
@jeanbisutti Did the fix for the GCP

**Comment by jeanbisutti** [comment]
@brunobat I have fixed a problem related to the documentation.

There is now a problem with the Azure test in the native mode:

```
Caused by: java.net.MalformedURLException: Accessing a URL protocol that was not enabled. The URL protocol https is supported but not enabled by default. It must be enabled by adding the --enable-url-protocols=https option to the native-image command.
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.JavaNetSubstitutions.unsupported(JavaNetSubstitutions.java:253)
```

It may be related to a Mandrel release 3 days ago: https://github.com/graalvm/mandrel/releases/tag/mandrel-23.1.4.0-Final

CI log:

`[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on MANDREL 23.1.4.0 JDK 21.0.4+7-LTS`

What would you recommend to fix this?

**Comment by brunobat** [comment]
@jeanbisutti for some reason SSL was being set as disabled... I'm forcing it to be active and removed a redundant dependency causing problems with the build.

**Review by brunobat — APPROVED** [review]

**Pull request merged**
