### PR TITLE
Use AutoConfiguredOpenTelemetrySdkBuilderCustomizer for Azure

### PR DESCRIPTION
**Pull request by jeanbisutti**

### CODE REVIEW

**Review by brunobat — APPROVED** [review]
Excellent! Thanks very much!

**Comment by hungchu0912** [comment]
Hello @jeanbisutti @brunobat when will this changes available on release? I checked the latest version 3.8.3.1 and it does not include this change.
I am finding a way to using AzureMonitorLogRecordExporter to get the data available on Application Insight's traces table, and seem like this change got it covered, the current version only supports AzureMonitorTraceExporter

**Comment by brunobat** [comment]
Will book some time for start of next week, @hungchu0912.

**Comment by jeanbisutti** [comment]
Hi @hungchu0912, It seems you would like your application logs available in Application Insights? To do this, it would require this PR and the instrumentation of the Quarkus logs that should be available in the Quarkus release on Oct 30.

**Comment by brunobat** [comment]
That is true. OTel Logs will only be available on Quarkus 3.16.

**Comment by jeanbisutti** [comment]
@hungchu0912 

`quarkus-opentelemetry-exporter-azure` 3.16.2 is now released.

You can set the `quarkus.otel.logs.enabled` property to `true`  and check that the logs of your Quarkus native app are in the traces table.

**Comment by hungchu0912** [comment]
Hello @jeanbisutti , sorry for the late response, i have just tried the latest version and config you mentioned, now i can see logs are properly propagated into the traces table in Application Insight. Much appreciate your contribution 👍

**Pull request merged**
